// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: feQAHrCNoVA9TpipNUrgy5
// Component: XHo9xHY34C
import * as React from "react";
import Link from "next/link";
import * as p from "@plasmicapp/react-web";
import * as ph from "@plasmicapp/host";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariants_6ZOnqyGdYzmB } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: 6zONQYGdYzmB_/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: feQAHrCNoVA9TpipNUrgy5/projectcss
import sty from "./PlasmicCard.module.css"; // plasmic-import: XHo9xHY34C/css
import Icon29Icon from "./icons/PlasmicIcon__Icon29"; // plasmic-import: ZnuAWf87MEWZ/icon
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: GvqPuQPXDTx7/icon
import Icon4Icon from "./icons/PlasmicIcon__Icon4"; // plasmic-import: 5q9Mz1Ss37Lf/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: vieOYW1zlBi4/icon

export const PlasmicCard__VariantProps = new Array();

export const PlasmicCard__ArgProps = new Array();

function PlasmicCard__RenderFunc(props) {
  const { variants, overrides, forNode } = props;
  const $ctx = ph.useDataEnv?.() || {};
  const args = React.useMemo(() => Object.assign({}, props.args), [props.args]);
  const $props = {
    ...args,
    ...variants
  };
  const currentUser = p.useCurrentUser?.() || {};
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants_6ZOnqyGdYzmB()
  });
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        sty.root
      )}
    >
      <div
        className={classNames(
          projectcss.all,
          projectcss.__wab_text,
          sty.text__pq83L
        )}
      >
        {"Woah, this is pretty cool!"}
      </div>

      <div className={classNames(projectcss.all, sty.freeBox__g1Hu)}>
        {true ? (
          <p.Stack
            as={"div"}
            data-plasmic-name={"header"}
            data-plasmic-override={overrides.header}
            hasGap={true}
            className={classNames(projectcss.all, sty.header)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__jjxeh)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__oj3OT)}
              >
                {true ? (
                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__opHfk
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    <p.PlasmicImg
                      alt={""}
                      className={classNames(sty.img___89L0V)}
                      displayHeight={"78px"}
                      displayMaxHeight={"none"}
                      displayMaxWidth={"78px"}
                      displayMinHeight={"0"}
                      displayMinWidth={"0"}
                      displayWidth={"100%"}
                      src={"/plasmic/blank_project/images/image.svg"}
                    />
                  </p.PlasmicLink>
                ) : null}

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__gbVuv)}
                >
                  <p.Stack
                    as={p.PlasmicLink}
                    data-plasmic-name={"aboutUs"}
                    data-plasmic-override={overrides.aboutUs}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.aboutUs
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__tHgOc)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__pBbT
                      )}
                    >
                      {"About Us"}
                    </div>

                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__ogIcL)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__pIaIz
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__nB63D)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__yg2Bi
                      )}
                    >
                      {"Services"}
                    </div>

                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__tVahn)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__juRuw
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__xbSru)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text__s7Lb7
                      )}
                    >
                      {"Clients"}
                    </div>

                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__pFua)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__axOy4
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__psjag)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___05Ae9
                      )}
                    >
                      {"Blog"}
                    </div>

                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg___2Iehg)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>

                  <p.Stack
                    as={p.PlasmicLink}
                    hasGap={true}
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      sty.link__oAvxw
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__e0CE)}
                        role={"img"}
                      />
                    ) : null}

                    <div
                      data-plasmic-name={"contact"}
                      data-plasmic-override={overrides.contact}
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.contact
                      )}
                    >
                      {"Contact Us"}
                    </div>

                    {false ? (
                      <Icon29Icon
                        className={classNames(projectcss.all, sty.svg__xnOna)}
                        role={"img"}
                      />
                    ) : null}
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </p.Stack>
        ) : null}

        <div
          data-plasmic-name={"aboutUsBanner"}
          data-plasmic-override={overrides.aboutUsBanner}
          className={classNames(projectcss.all, sty.aboutUsBanner)}
        >
          <p.Stack
            as={"div"}
            data-plasmic-name={"foreground2"}
            data-plasmic-override={overrides.foreground2}
            hasGap={true}
            className={classNames(projectcss.all, sty.foreground2)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox___4ABr)}
            >
              <h1
                className={classNames(
                  projectcss.all,
                  projectcss.h1,
                  projectcss.__wab_text,
                  sty.h1__ociMc
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "About US"
                  : "About Us"}
              </h1>

              <div
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text__nIpqb
                )}
              >
                {hasVariant(globalVariants, "screen", "mobileOnly")
                  ? "Lorem Ipsum is simply dummy text of the printing and typesetting industry."
                  : "Lorem Ipsum is simply dummy text of the printing and typesetting industry."}
              </div>
            </p.Stack>
          </p.Stack>
        </div>

        {true ? (
          <div
            data-plasmic-name={"ourTeamSection"}
            data-plasmic-override={overrides.ourTeamSection}
            className={classNames(projectcss.all, sty.ourTeamSection)}
          >
            <div
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              className={classNames(projectcss.all, sty.columns)}
            >
              <div className={classNames(projectcss.all, sty.column__yiLs)}>
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__eoDkR
                  )}
                >
                  {"Our team"}
                </h2>

                <div
                  data-plasmic-name={"container"}
                  data-plasmic-override={overrides.container}
                  className={classNames(projectcss.all, sty.container)}
                >
                  <p.Stack
                    as={"div"}
                    data-plasmic-name={"row1"}
                    data-plasmic-override={overrides.row1}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.row1)}
                  >
                    <div
                      className={classNames(projectcss.all, sty.column__adt4D)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bHk69
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__aMz7L)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox___7YT2C
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__xq9V
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__s4Z0Y
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__bMct
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__nbDe3
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>

                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__mknCy
                              )}
                            >
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__kppZf
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__fbX8
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__w6Qqk
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon4Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__zDuUc
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__bR3Of
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon5Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wqYlo
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__l75Y0)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox___7ENpL
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__pr7I0)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__j7F6Z
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__jSwX5
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__nW2KM
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__nqbrm
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__biGGc
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>

                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__pOgW
                              )}
                            >
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__naeah
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__uOgNg
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__foFY
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon4Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__iyvI0
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__cLrWf
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon5Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___9Yhq9
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__eeUhx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__yC0V1
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__iEYeP)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qmvE
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__krqxf
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__ad8Jj
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uV2Qy
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__co804
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>

                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__rm3Fm
                              )}
                            >
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__c0Lwn
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__zl2Bf
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link___2QyMs
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon4Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__wGwZw
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__hl5H6
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon5Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__isDt6
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__nm3Do)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__e1YDg
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__s1Qgs)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__iWhfm
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__yPrQs
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3___00RKb
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___37Adq
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__lJtUo
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>

                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__juaXu
                              )}
                            >
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__lep8
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__hu7Ln
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__kAvTj
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon4Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__os25L
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__phjLl
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon5Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___3FlQs
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__qhWUx)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__da8R8
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__yfCkv)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__y54
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__fnxxc
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__mvhty
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__gQzjD
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__xedOu
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>

                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__jiKoi
                              )}
                            >
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__zaHJp
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___9UQ7N
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__rpti
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon4Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___9LZnN
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__mqYaP
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon5Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg___0WOrJ
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      </div>
                    </div>

                    <div
                      className={classNames(projectcss.all, sty.column__lq4Vb)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__l6Cz
                        )}
                      >
                        <p.PlasmicImg
                          alt={""}
                          className={classNames(sty.img__xFgSg)}
                          displayHeight={"336px"}
                          displayMaxHeight={"none"}
                          displayMaxWidth={"100%"}
                          displayMinHeight={"0"}
                          displayMinWidth={"0"}
                          displayWidth={"100%"}
                          loading={"lazy"}
                        />

                        <p.Stack
                          as={"div"}
                          hasGap={true}
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__t94Rm
                          )}
                        >
                          <h1
                            className={classNames(
                              projectcss.all,
                              projectcss.h1,
                              sty.h1__zB9H3
                            )}
                          >
                            <h3
                              className={classNames(
                                projectcss.all,
                                projectcss.h3,
                                projectcss.__wab_text,
                                sty.h3__dXkSq
                              )}
                            >
                              {"Lorem Ipsum"}
                            </h3>
                          </h1>

                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox___3DOnh
                            )}
                          >
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__uUoLy
                              )}
                            >
                              {"Job title"}
                            </div>
                          </div>

                          {true ? (
                            <p.Stack
                              as={"div"}
                              hasGap={true}
                              className={classNames(
                                projectcss.all,
                                sty.freeBox__fxqnm
                              )}
                            >
                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__hr007
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon3Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__qkYqc
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__dVkuV
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon4Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__dRjRi
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>

                              <p.PlasmicLink
                                className={classNames(
                                  projectcss.all,
                                  projectcss.a,
                                  sty.link__mHhFf
                                )}
                                component={Link}
                                platform={"nextjs"}
                              >
                                <Icon5Icon
                                  className={classNames(
                                    projectcss.all,
                                    sty.svg__piJda
                                  )}
                                  role={"img"}
                                />
                              </p.PlasmicLink>
                            </p.Stack>
                          ) : null}
                        </p.Stack>
                      </div>
                    </div>
                  </p.Stack>
                </div>
              </div>
            </div>
          </div>
        ) : null}

        <div className={classNames(projectcss.all, sty.freeBox__jIvGc)}>
          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(projectcss.all, sty.freeBox__coQrp)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(projectcss.all, sty.freeBox__nAZn)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yiL7O)}
              >
                <h2
                  className={classNames(
                    projectcss.all,
                    projectcss.h2,
                    projectcss.__wab_text,
                    sty.h2__jAwQ6
                  )}
                >
                  {"Our values"}
                </h2>

                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__twWuy
                  )}
                >
                  {
                    "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                  }
                </div>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(projectcss.all, sty.freeBox__yu6Ld)}
              >
                <p.Stack
                  as={"div"}
                  data-plasmic-name={"serviceRow"}
                  data-plasmic-override={overrides.serviceRow}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.serviceRow)}
                >
                  <div
                    className={classNames(projectcss.all, sty.column___7CIgt)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__bvl2A
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__cbW
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__txKc0
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__jiQ4
                            )}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qrn4A
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___1KdI
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__dfO8Z)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ha0Nf
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__otrIj
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___6J16Z
                            )}
                          >
                            {"Service"}
                          </h3>
                        </h3>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__vH6Y8
                            )}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__qtKln
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__wZHb
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__veTiu)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(projectcss.all, sty.freeBox__pHq)}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__fhpFu
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__u1YDp
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__dOhDu
                            )}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__mBvkF
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__bwRep
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__b0SYv)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__tu6LF
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__gyYRx
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___5SZch
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__eQn
                            )}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__eiiLa
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__rpk1D
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__enjzH)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__a4MQg
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__cvbKi
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3__q6Ew6
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__zKeR2
                            )}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gvQy4
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text__jkb4U
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>

                  <div
                    className={classNames(projectcss.all, sty.column__hXhGa)}
                  >
                    {true ? (
                      <p.Stack
                        as={"div"}
                        hasGap={true}
                        className={classNames(
                          projectcss.all,
                          sty.freeBox__ko5Sw
                        )}
                      >
                        <h3
                          className={classNames(
                            projectcss.all,
                            projectcss.h3,
                            sty.h3__mnNpr
                          )}
                        >
                          <h3
                            className={classNames(
                              projectcss.all,
                              projectcss.h3,
                              projectcss.__wab_text,
                              sty.h3___4C3Q5
                            )}
                          >
                            {"Value"}
                          </h3>
                        </h3>

                        {true ? (
                          <div
                            className={classNames(
                              projectcss.all,
                              sty.freeBox__uib4C
                            )}
                          />
                        ) : null}

                        <div
                          className={classNames(
                            projectcss.all,
                            sty.freeBox__gBrD
                          )}
                        >
                          <div
                            className={classNames(
                              projectcss.all,
                              projectcss.__wab_text,
                              sty.text___252Qc
                            )}
                          >
                            {
                              "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s,"
                            }
                          </div>
                        </div>
                      </p.Stack>
                    ) : null}
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </p.Stack>
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__dmKfv)}>
          <div className={classNames(projectcss.all, sty.freeBox__mmb7N)}>
            <div className={classNames(projectcss.all, sty.freeBox__ohZOk)}>
              <p.Stack
                as={"div"}
                data-plasmic-name={"foreground3"}
                data-plasmic-override={overrides.foreground3}
                hasGap={true}
                className={classNames(projectcss.all, sty.foreground3)}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__y2Y1P)}
                >
                  <h2
                    className={classNames(
                      projectcss.all,
                      projectcss.h2,
                      projectcss.__wab_text,
                      sty.h2__ceAn6
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Take your business to the next level"
                      : "Work with us."}
                  </h2>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__rrRud
                    )}
                  >
                    {hasVariant(globalVariants, "screen", "mobileOnly")
                      ? "Rapidiously revolutionize future-proof niches, and authoritatively \nrestore user-centric e-markets."
                      : "Lorem Ipsum is simply dummy text of the printing and typesetting industry. "}
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__e9YnY)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(projectcss.all, sty.freeBox___0Qjbm)}
                  >
                    <p.Stack
                      as={"button"}
                      data-plasmic-name={"button"}
                      data-plasmic-override={overrides.button}
                      hasGap={true}
                      className={classNames(
                        projectcss.all,
                        projectcss.button,
                        sty.button
                      )}
                    >
                      {false ? (
                        <Icon29Icon
                          className={classNames(
                            projectcss.all,
                            sty.svg___3LUgK
                          )}
                          role={"img"}
                        />
                      ) : null}

                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__lgqch
                        )}
                      >
                        {"Get IN Touch"}
                      </div>

                      {false ? (
                        <Icon29Icon
                          className={classNames(projectcss.all, sty.svg__e6JyJ)}
                          role={"img"}
                        />
                      ) : null}
                    </p.Stack>
                  </p.Stack>
                </p.Stack>
              </p.Stack>
            </div>
          </div>
        </div>

        <div className={classNames(projectcss.all, sty.freeBox__u6GHa)}>
          {true ? (
            <div className={classNames(projectcss.all, sty.freeBox__em2TY)}>
              <p.Stack
                as={"div"}
                data-plasmic-name={"rowWrapper"}
                data-plasmic-override={overrides.rowWrapper}
                hasGap={true}
                className={classNames(projectcss.all, sty.rowWrapper)}
              >
                <div
                  data-plasmic-name={"colmn1"}
                  data-plasmic-override={overrides.colmn1}
                  className={classNames(projectcss.all, sty.colmn1)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__jYBhZ
                    )}
                  >
                    {"About us"}
                  </h3>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__aHzVl
                    )}
                  >
                    <React.Fragment>
                      <React.Fragment>
                        {
                          "© Company. All rights reserved. This site proudly built with "
                        }
                      </React.Fragment>
                      {
                        <p.PlasmicLink
                          className={classNames(
                            projectcss.all,
                            projectcss.a,
                            projectcss.__wab_text,
                            projectcss.plasmic_default__inline,
                            sty.link__mZzQo
                          )}
                          component={Link}
                          href={"https://www.plasmic.app"}
                          platform={"nextjs"}
                        >
                          {"Plasmic"}
                        </p.PlasmicLink>
                      }

                      <React.Fragment>{"."}</React.Fragment>
                    </React.Fragment>
                  </div>
                </div>

                <div
                  data-plasmic-name={"colmn2"}
                  data-plasmic-override={overrides.colmn2}
                  className={classNames(projectcss.all, sty.colmn2)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3___3N5Tv
                    )}
                  >
                    {"Links"}
                  </h3>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__jrOi
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Services"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__csQxc
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ocwch
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"Testimonials"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__saIh
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"Blog"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rjWgJ
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Contact us\n"}
                  </p.PlasmicLink>
                </div>

                <div
                  data-plasmic-name={"colmn22"}
                  data-plasmic-override={overrides.colmn22}
                  className={classNames(projectcss.all, sty.colmn22)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3__pAyYk
                    )}
                  >
                    {"Nav Links"}
                  </h3>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__wGbHs
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Services"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link___118L
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"About us"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__xvKNu
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Testimonials"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__ugp4H
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"Blog"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__tBo7Z
                    )}
                    component={Link}
                    platform={"nextjs"}
                  >
                    {"Contact us\n"}
                  </p.PlasmicLink>
                </div>

                <div
                  data-plasmic-name={"colmn3"}
                  data-plasmic-override={overrides.colmn3}
                  className={classNames(projectcss.all, sty.colmn3)}
                >
                  <h3
                    className={classNames(
                      projectcss.all,
                      projectcss.h3,
                      projectcss.__wab_text,
                      sty.h3___0JF5Q
                    )}
                  >
                    {"Contact "}
                  </h3>

                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___1SBn
                    )}
                  >
                    {"1234 Lorem Ipsum .\nLorem Ipsum , GA 30308"}
                  </div>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__rHSgr
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"xyz@company.com"}
                  </p.PlasmicLink>

                  <p.PlasmicLink
                    className={classNames(
                      projectcss.all,
                      projectcss.a,
                      projectcss.__wab_text,
                      sty.link__zlK0
                    )}
                    component={Link}
                    href={"#"}
                    platform={"nextjs"}
                  >
                    {"1234567890"}
                  </p.PlasmicLink>
                </div>
              </p.Stack>
            </div>
          ) : null}
        </div>

        <div
          className={classNames(
            projectcss.all,
            projectcss.__wab_text,
            sty.text__od1B
          )}
        >
          {"4YrBzHxMn6W13k5gQFZJjjMmgy32"}
        </div>
      </div>
    </div>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "header",
    "aboutUs",
    "contact",
    "aboutUsBanner",
    "foreground2",
    "ourTeamSection",
    "columns",
    "container",
    "row1",
    "serviceRow",
    "foreground3",
    "button",
    "rowWrapper",
    "colmn1",
    "colmn2",
    "colmn22",
    "colmn3"
  ],

  header: ["header", "aboutUs", "contact"],
  aboutUs: ["aboutUs"],
  contact: ["contact"],
  aboutUsBanner: ["aboutUsBanner", "foreground2"],
  foreground2: ["foreground2"],
  ourTeamSection: ["ourTeamSection", "columns", "container", "row1"],
  columns: ["columns", "container", "row1"],
  container: ["container", "row1"],
  row1: ["row1"],
  serviceRow: ["serviceRow"],
  foreground3: ["foreground3", "button"],
  button: ["button"],
  rowWrapper: ["rowWrapper", "colmn1", "colmn2", "colmn22", "colmn3"],
  colmn1: ["colmn1"],
  colmn2: ["colmn2"],
  colmn22: ["colmn22"],
  colmn3: ["colmn3"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: [...PlasmicDescendants[nodeName]],
          internalArgPropNames: PlasmicCard__ArgProps,
          internalVariantPropNames: PlasmicCard__VariantProps
        }),
      [props, nodeName]
    );

    return PlasmicCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCard";
  } else {
    func.displayName = `PlasmicCard.${nodeName}`;
  }
  return func;
}

export const PlasmicCard = Object.assign(
  // Top-level PlasmicCard renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    header: makeNodeComponent("header"),
    aboutUs: makeNodeComponent("aboutUs"),
    contact: makeNodeComponent("contact"),
    aboutUsBanner: makeNodeComponent("aboutUsBanner"),
    foreground2: makeNodeComponent("foreground2"),
    ourTeamSection: makeNodeComponent("ourTeamSection"),
    columns: makeNodeComponent("columns"),
    container: makeNodeComponent("container"),
    row1: makeNodeComponent("row1"),
    serviceRow: makeNodeComponent("serviceRow"),
    foreground3: makeNodeComponent("foreground3"),
    button: makeNodeComponent("button"),
    rowWrapper: makeNodeComponent("rowWrapper"),
    colmn1: makeNodeComponent("colmn1"),
    colmn2: makeNodeComponent("colmn2"),
    colmn22: makeNodeComponent("colmn22"),
    colmn3: makeNodeComponent("colmn3"),
    // Metadata about props expected for PlasmicCard
    internalVariantProps: PlasmicCard__VariantProps,
    internalArgProps: PlasmicCard__ArgProps
  }
);

export default PlasmicCard;
/* prettier-ignore-end */
